Landing page rework
feelingapp/feeling-app pull request #8
Opened 2020-09-04 15:05 UTC by adamjhc

- [x] Rewrote css in linaria
- [x] Moved svgs into the assets folder
- [x] Removed tab bar from landing page

2020-09-04 16:00 UTC, pavsidhu requested changes

2020-09-04 16:00 UTC, pavsidhu commented on src/pages/landing/index.tsx
> +      content: "👉 ";
Niceee 👌🏼

2020-09-04 16:05 UTC, adamjhc commented on src/pages/landing/index.tsx
> +        <Link href="https://twitter.com/feelingapp">
sounds good to me

2020-09-04 16:06 UTC, adamjhc commented on src/pages/landing/index.tsx
> +    width: var(--grid-width);
yeah I realised while I was doing this it was the same as padding, mainly kept it bc it's what I had before and I set the width in the media queries

2020-09-04 16:06 UTC, adamjhc commented on src/pages/landing/index.tsx
> +      /* gap: 0; */
will do

2020-09-04 16:07 UTC, adamjhc commented on src/pages/landing/index.tsx
> +    --input-border-radius: 12px;
with a variety of sizes or just the one?

2020-09-04 16:07 UTC, adamjhc commented on src/pages/landing/index.tsx
> +    --input-padding: 15px;
yup think I already replaced them elsewhere actually, nice catch

2020-09-04 22:26 UTC, pavsidhu commented on src/pages/landing/index.tsx
> +    --input-border-radius: 12px;
nahh just --border-radius: 12px should be good 👍🏼

2020-09-08 10:28 UTC, adamjhc commented on src/pages/landing/index.tsx
> +    width: var(--grid-width);
Decided to leave this as-is for now because the grid-width property works with a lot of the other elements

2020-09-09 08:50 UTC, merged